ALTER TABLE devices ADD COLUMN IF NOT EXISTS model VARCHAR(64);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS sim_iccid VARCHAR(32);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS mobile_carrier VARCHAR(64);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS sms_command_password_encrypted TEXT;
